[monitor]
report = "127.0.0.1:8082"
daemon = "127.0.0.1:8083"
tick = 1.0
format = "json"
slope-history = 5
cpu-max-freq = 3000

[market]
base-cycle = 30.0
trigger-increment = 95.0
trigger-decrement = 50.0
decreasing-speed = 20.0
increasing-speed = 100.0	
window-size = 100000
